---
--- Generated by Luanalysis
--- Created by Desithy.
--- DateTime: 2023/12/22 20:46
---

--- 1.新建变量 优惠券id，用户id
local voucherId = ARGV[1]
local userId = ARGV[2]

--- 2.新建key  库存key  订单key
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

--- 3.判断库存是否充足

if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end

--- 4.判断用户是否下单 sismember orderKey orderID
if(redis.call('SISMEMBER',orderKey,userId) == 1) then
    return 2
end

--- 5.扣减库存 incrby stockKey -1
redis.call('incrby' , stockKey, -1)

redis.call('sadd', orderKey, userId)

return 0

